;--Settings file for the charms.
;--This file wont be overwritten when updating to new versions.

[Variables]
;--Example shown here.----------------------
;Charm00Image   = #CharmLoc#Kingsoul.png
;Charm00Path    = "C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight.exe"
;Charm00Title   = "Hollow Knight"
;Charm00Desc    = "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style."
;-------------------------------------------

;__Row 3 Charms__
Charm30Image    = #CharmLoc#Empty.png
Charm30Path     = *Set App Path Here*
Charm30Title    = ""
Charm30Desc     = ""

Charm31Image    = #CharmLoc#Empty.png
Charm31Path     = *Set App Path Here*
Charm31Title    = ""
Charm31Desc     = ""

Charm32Image    = #CharmLoc#Empty.png
Charm32Path     = *Set App Path Here*
Charm32Title    = ""
Charm32Desc     = ""

Charm33Image    = #CharmLoc#Empty.png 
Charm33Path     = *Set App Path Here*
Charm33Title    = ""
Charm33Desc     = ""

Charm34Image    = #CharmLoc#Empty.png
Charm34Path     = *Set App Path Here*
Charm34Title    = ""
Charm34Desc     = ""

Charm35Image    = #CharmLoc#Empty.png
Charm35Path     = *Set App Path Here*
Charm35Title    = ""
Charm35Desc     = ""

Charm36Image    = #CharmLoc#Empty.png
Charm36Path     = *Set App Path Here*
Charm36Title    = ""
Charm36Desc     = ""

Charm37Image    = #CharmLoc#Empty.png
Charm37Path     = *Set App Path Here*
Charm37Title    = ""
Charm37Desc     = ""

Charm38Image    = #CharmLoc#Empty.png
Charm38Path     = *Set App Path Here*
Charm38Title    = ""
Charm38Desc     = ""
