;--Settings file for the charms.
;--This file wont be overwritten when updating to new versions.

[Variables]
;--Example shown here.----------------------
;Charm00Image   = #CharmLoc#Kingsoul.png
;Charm00Path    = "C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight.exe"
;Charm00Title   = "Hollow Knight"
;Charm00Desc    = "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style."
;-------------------------------------------

;__Row 0 Charms__
Charm00Image    = #CharmLoc#Kingsoul.png
Charm00Path     = "C:/Program Files (x86)/Steam/steamapps/common/Hollow Knight/hollow_knight.exe"
Charm00Title    = "Hollow Knight"
Charm00Desc     = "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style."

Charm01Image    = #CharmLoc#Firefox.png
Charm01Path     = "C:/Program Files (x86)/Mozilla Firefox/firefox.exe"
Charm01Title    = "Mozilla Firefox"
Charm01Desc     = "Experience a fast, smart and personal Web. Firefox is the independent, people-first browser made by Mozilla, voted the Most Trusted Internet Company for Privacy. Upgrade today and join hundreds of millions who depend on Firefox for a more personal browsing experience."

Charm02Image    = #CharmLoc#Empty.png
Charm02Path     = *Set App Path Here*
Charm02Title    = ""
Charm02Desc     = ""

Charm03Image    = #CharmLoc#Empty.png
Charm03Path     = *Set App Path Here*
Charm03Title    = ""
Charm03Desc     = ""

Charm04Image    = #CharmLoc#Empty.png
Charm04Path     = *Set App Path Here*
Charm04Title    = ""
Charm04Desc     = ""

Charm05Image    = #CharmLoc#Empty.png
Charm05Path     = *Set App Path Here*
Charm05Title    = ""
Charm05Desc     = ""

Charm06Image    = #CharmLoc#Empty.png
Charm06Path     = *Set App Path Here*
Charm06Title    = ""
Charm06Desc     = ""

Charm07Image    = #CharmLoc#Empty.png
Charm07Path     = *Set App Path Here*
Charm07Title    = ""
Charm07Desc     = ""

Charm08Image    = #CharmLoc#Empty.png
Charm08Path     = *Set App Path Here*
Charm08Title    = ""
Charm08Desc     = ""