;--Settings file for the charms.
;--This file wont be overwritten when updating to new versions.

[Variables]
;--Example shown here.----------------------
;Charm00Image   = #CharmLoc#Kingsoul.png
;Charm00Path    = "C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight.exe"
;Charm00Title   = "Hollow Knight"
;Charm00Desc    = "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style."
;-------------------------------------------

;__Row 1 Charms__
Charm10Image    = #CharmLoc#Empty.png
Charm10Path     = *Set App Path Here*
Charm10Title    = ""
Charm10Desc     = ""

Charm11Image    = #CharmLoc#Empty.png
Charm11Path     = *Set App Path Here*
Charm11Title    = ""
Charm11Desc     = ""

Charm12Image    = #CharmLoc#Empty.png
Charm12Path     = *Set App Path Here*
Charm12Title    = ""
Charm12Desc     = ""

Charm13Image    = #CharmLoc#Empty.png
Charm13Path     = *Set App Path Here*
Charm13Title    = ""
Charm13Desc     = ""

Charm14Image    = #CharmLoc#Empty.png
Charm14Path     = *Set App Path Here*
Charm14Title    = ""
Charm14Desc     = ""

Charm15Image    = #CharmLoc#Empty.png
Charm15Path     = *Set App Path Here*
Charm15Title    = ""
Charm15Desc     = ""

Charm16Image    = #CharmLoc#Empty.png
Charm16Path     = *Set App Path Here*
Charm16Title    = ""
Charm16Desc     = ""

Charm17Image    = #CharmLoc#Empty.png
Charm17Path     = *Set App Path Here*
Charm17Title    = ""
Charm17Desc     = ""

Charm18Image    = #CharmLoc#Empty.png
Charm18Path     = *Set App Path Here*
Charm18Title    = ""
Charm18Desc     = ""