;--Settings file for the charms.
;--This file wont be overwritten when updating to new versions.

[Variables]
;--Example shown here.----------------------
;Charm00Image   = #CharmLoc#Kingsoul.png
;Charm00Path    = "C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight.exe"
;Charm00Title   = "Hollow Knight"
;Charm00Desc    = "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style."
;-------------------------------------------

;__Row 2 Charms__
Charm20Image    = #CharmLoc#Empty.png
Charm20Path     = *Set App Path Here*
Charm20Title    = ""
Charm20Desc     = ""

Charm21Image    = #CharmLoc#Empty.png
Charm21Path     = *Set App Path Here*
Charm21Title    = ""
Charm21Desc     = ""

Charm22Image    = #CharmLoc#Empty.png
Charm22Path     = *Set App Path Here*
Charm22Title    = ""
Charm22Desc     = ""

Charm23Image    = #CharmLoc#Empty.png
Charm23Path     = *Set App Path Here*
Charm23Title    = ""
Charm23Desc     = ""

Charm24Image    = #CharmLoc#Empty.png
Charm24Path     = *Set App Path Here*
Charm24Title    = ""
Charm24Desc     = ""

Charm25Image    = #CharmLoc#Empty.png
Charm25Path     = *Set App Path Here*
Charm25Title    = ""
Charm25Desc     = ""

Charm26Image    = #CharmLoc#Empty.png
Charm26Path     = *Set App Path Here*
Charm26itle    = ""
Charm26Desc     = ""

Charm27Image    = #CharmLoc#Empty.png
Charm27Path     = *Set App Path Here*
Charm27Title    = ""
Charm27Desc     = ""

Charm28Image    = #CharmLoc#Empty.png
Charm28Path     = *Set App Path Here*
Charm28Title    = ""
Charm28Desc     = ""