;--Settings file for the charms.
;--This file wont be overwritten when updating to new versions.

[Variables]
;--Example shown here.----------------------
;Charm00Image   = #CharmLoc#Kingsoul.png
;Charm00Path    = "C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight.exe"
;-------------------------------------------

;__Row 0 Charms__
Charm00Image    = #CharmLoc#Kingsoul.png
Charm00Path     = "C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight.exe"
Charm00Name     = "Hollow Knight"
Charm00Desc     = "Award-winning adventure platformer!"

Charm01Image    = #CharmLoc#Firefox.png
Charm01Path     = "C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
Charm01Name     = "Firefox"
Charm01Desc     = "The fastest browser around!"

Charm02Image    = #CharmLoc#Empty.png
Charm02Path     = *Set App Path Here*

Charm03Image    = #CharmLoc#Empty.png
Charm03Path     = *Set App Path Here*

Charm04Image    = #CharmLoc#Empty.png
Charm04Path     = *Set App Path Here*

Charm05Image    = #CharmLoc#Empty.png
Charm05Path     = *Set App Path Here*

Charm06Image    = #CharmLoc#Empty.png
Charm06Path     = *Set App Path Here*

Charm07Image    = #CharmLoc#Empty.png
Charm07Path     = *Set App Path Here*

Charm08Image    = #CharmLoc#Empty.png
Charm08Path     = *Set App Path Here*

;__Row 1 Charms__
Charm10Image    = #CharmLoc#Empty.png
Charm10Path     = *Set App Path Here*

Charm11Image    = #CharmLoc#Empty.png
Charm11Path     = *Set App Path Here*

Charm12Image    = #CharmLoc#Empty.png
Charm12Path     = *Set App Path Here*

Charm13Image    = #CharmLoc#Empty.png
Charm13Path     = *Set App Path Here*

Charm14Image    = #CharmLoc#Empty.png
Charm14Path     = *Set App Path Here*

Charm15Image    = #CharmLoc#Empty.png
Charm15Path     = *Set App Path Here*

Charm16Image    = #CharmLoc#Empty.png
Charm16Path     = *Set App Path Here*

Charm17Image    = #CharmLoc#Empty.png
Charm17Path     = *Set App Path Here*

Charm18Image    = #CharmLoc#Empty.png
Charm18Path     = *Set App Path Here*

;__Row 2 Charms__
Charm20Image    = #CharmLoc#Empty.png
Charm20Path     = *Set App Path Here*

Charm21Image    = #CharmLoc#Empty.png
Charm21Path     = *Set App Path Here*

Charm22Image    = #CharmLoc#Empty.png
Charm22Path     = *Set App Path Here*

Charm23Image    = #CharmLoc#Empty.png
Charm23Path     = *Set App Path Here*

Charm24Image    = #CharmLoc#Empty.png
Charm24Path     = *Set App Path Here*

Charm25Image    = #CharmLoc#Empty.png
Charm25Path     = *Set App Path Here*

Charm26Image    = #CharmLoc#Empty.png
Charm26Path     = *Set App Path Here*

Charm27Image    = #CharmLoc#Empty.png
Charm27Path     = *Set App Path Here*

Charm28Image    = #CharmLoc#Empty.png
Charm28Path     = *Set App Path Here*

;__Row 3 Charms__
Charm30Image    = #CharmLoc#Empty.png
Charm30Path     = *Set App Path Here*

Charm31Image    = #CharmLoc#Empty.png
Charm31Path     = *Set App Path Here*

Charm32Image    = #CharmLoc#Empty.png
Charm32Path     = *Set App Path Here*

Charm33Image    = #CharmLoc#Empty.png
Charm33Path     = *Set App Path Here*

Charm34Image    = #CharmLoc#Empty.png
Charm34Path     = *Set App Path Here*

Charm35Image    = #CharmLoc#Empty.png
Charm35Path     = *Set App Path Here*

Charm36Image    = #CharmLoc#Empty.png
Charm36Path     = *Set App Path Here*

Charm37Image    = #CharmLoc#Empty.png
Charm37Path     = *Set App Path Here*

Charm38Image    = #CharmLoc#Empty.png
Charm38Path     = *Set App Path Here*